name: drivepulse
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  nb_utils: ^7.0.3
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.10.0
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  syncfusion_flutter_gauges: ^26.1.42
  syncfusion_flutter_charts: ^26.1.42
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  rename_app: ^1.6.2
  cloud_firestore: ^5.6.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo-b.png
  android_12:
    image: assets/images/logo-b.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  image_path: "assets/images/logo-a.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/splash.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/splash.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/splash.png"
