// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YH43ivRDMc0pK9_ZlNK-yOvX-znBv4c',
    appId: '1:290756666298:android:6b37213f37e557dd60f383',
    messagingSenderId: '290756666298',
    projectId: 'drivepulse-71a4a',
    storageBucket: 'drivepulse-71a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXMl8zF1WIFLUR-K3JyLY4jdXW8R7V_xk',
    appId: '1:290756666298:ios:6caefdde2aa1d50360f383',
    messagingSenderId: '290756666298',
    projectId: 'drivepulse-71a4a',
    storageBucket: 'drivepulse-71a4a.appspot.com',
    androidClientId: '290756666298-mkihhfnub1t98t906tscdgvffg043ppg.apps.googleusercontent.com',
    iosClientId: '290756666298-hf2ojftfbr9sbjuku0p9vut7aq10cccc.apps.googleusercontent.com',
    iosBundleId: 'com.kp23242.drivepulse',
  );
}
